const APP_KEY = "YOUR_TWITTER_APP_KEY";
const APP_SECRET = "YOUR_TWITTER_APP_SECRET";
const ACCESS_TOKEN = "YOUR_TWITTER_ACCESS_TOKEN";
const ACCESS_SECRET = "YOUR_TWITTER_ACCESS_SECRET";
const GEMINI_API_KEY = "YOUR_GEMINI_API_KEY";

const SECRETS = {
  APP_KEY,
  APP_SECRET,
  ACCESS_TOKEN,
  ACCESS_SECRET,
  GEMINI_API_KEY,
};

module.exports = SECRETS;
